version: 2
jobs:
  test:
    docker:
      - image: circleci/node:11.4.0
    steps:
      - run: npm run test:coverage
  build:
    docker:
      - image: circleci/node:11.4.0
    steps:
      - run: echo "Build"
  publish:
    docker:
      - image: circleci/node:11.4.0
    steps:
      - run: echo "Publish"
workflows:
  version: 2
  golive:
    jobs:
      - test
      - build
      - publish
  