version: 2
jobs:
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/node:10.14.1 
    steps: # a collection of executable commands
      - checkout
      - run:
          name: liste
          command: ls
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test:coverage
          command: npm run test:coverage
      - store_artifacts:
          path: coverage # special step to upload test results for display in Test Summary